apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-replicationcontroller
spec:
  replicas: 2
  selector:
    app: myfirst-app
  template:
    metadata:
      name: myfirstapp-replicationcontroller
      labels:
        app: myfirst-app
    spec:
      containers:
        - name: rc-demo
          image: nginx
          ports:
          - name: tomcatport
            containerPort: 80
