apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp-dep
  template:
    metadata:
      labels:
        app: myapp-dep
    spec:
      containers:
      - name: myapp-deploy-test
        image: nginx:1.20.2
        ports:
        - containerPort: 80
      nodeSelector:
        env: dev
